In [1]:
import numpy as np
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,80])
print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 80]


numpy.ndarray

In [5]:
mon_array_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(mon_array_bidimensionnel [0] [2])
print(mon_array_bidimensionnel [0,2])
print(mon_array_bidimensionnel [:,0])
print(mon_array_bidimensionnel [0,:])


3
3
[1 4 7]
[1 2 3]


In [11]:
mon_array_bidimensionnel[0,0]="texte"


ValueError: invalid literal for int() with base 10: 'texte'

In [15]:
# mon_array_bidimensionnel[0,0]=1
# print(mon_array_bidimensionnel)

In [18]:
mon_array_bidimensionnel.dtype

dtype('int64')

In [19]:
mon_array_bidimensionnel=np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float64')

In [26]:
import numpy as np
mon_array_zeros=np.zeros((4,6))
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [28]:
import numpy as np
mon_array_ones=np.ones((4,6), dtype=int)
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [29]:
import numpy as np
mon_array_random=np.random.random((4,2))
print(mon_array_random)

[[0.10799422 0.33226083]
 [0.20717649 0.23679302]
 [0.1347682  0.49857065]
 [0.27045625 0.78158021]]


In [3]:
import numpy as np
iris=np.genfromtxt("iris.csv", delimiter=";", skip_header=True, encoding="latin-1")

print(iris)
iris.dtype
type(iris)


[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [5]:
import numpy as np
np.savetxt("iris.csv", iris, delimiter=";")

In [1]:
%pwd

'/home/simplon/Documents/test'

In [6]:
iris[2,1]#ligne,col

3.2

In [7]:
iris[2,1]

3.2

In [9]:
iris[2,1]=4
iris[2,1]

4.0

In [10]:
iris[2,1]=3.2#modif val
iris[2,1]

3.2

In [11]:
iris[iris>2]

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [13]:
iris[iris>2].shape[0]

472

In [14]:
iris>2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [16]:
iris[iris[:,0] >5]

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [5.5, 3.5, 1.3, 0.2, 1. ],
       [5.1, 3.4, 1.5, 0.2, 1. ],
       [5.1, 3.8, 1.9, 0.4, 1. ],
       [5.1, 3.8, 1.6, 0.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 1. ],
       [7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [6.6, 2

In [17]:
iris[:,0]>5 #masque

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [18]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("contenu de notre_tableau :")
print(notre_tableau)
print("nouveau tableau après fancy indexing :")
indices = np.array([[4,10,5],[12,8,9]])
print(notre_tableau[indices])

contenu de notre_tableau :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
nouveau tableau après fancy indexing :
[[ 5 11  6]
 [13  9 10]]


In [19]:
notre_tableau[:3] #les 3 premiers elements

array([1, 2, 3])

In [20]:
notre_tableau[10:]#les derniers à partir de l'index

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
notre_tableau[3:7] # du 3 au 7 elements

array([4, 5, 6, 7])

In [22]:
# tous les elements avec 1 pas de 2
notre_tableau[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
# tableau à 2 dimensions

#ici on selectionne les 2 premieres lignes des 4 premieres colonnes

iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [25]:
# les derniers lignes a partir de l'index

iris[145:,2:]

array([[5.2, 2.3, 3. ],
       [5. , 1.9, 3. ],
       [5.2, 2. , 3. ],
       [5.4, 2.3, 3. ],
       [5.1, 1.8, 3. ]])

In [26]:
#affiche ttes les col
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [27]:
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [28]:
#affiche tte les col de la derniere ligne
iris[-1,:]

array([5.9, 3. , 5.1, 1.8, 3. ])

In [29]:
#notion de vue et copie

sous_tableau=notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [30]:
sous_tableau[0]=10
sous_tableau # ! modifie

array([10,  2,  3,  4,  5])

In [31]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
# pour eviter cela .copy

notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
sous_tableau=notre_tableau[:5].copy()
sous_tableau[0]=10
print(sous_tableau)
print(notre_tableau)


[10  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [34]:
mon_tableau=np.array([[10,11,12],[13,14,15],[16,17,18]])
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [35]:
import numpy as np
np.add(mon_tableau,10)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [36]:
np.multiply(mon_tableau,20)

array([[200, 220, 240],
       [260, 280, 300],
       [320, 340, 360]])

In [37]:
mon_tableau2=np.array([10,20,30])
mon_tableau2
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [39]:
# soustraction avec arguments
import numpy as np
np.subtract(mon_tableau,mon_tableau2)

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [41]:
mon_tableau3=np.array=np.array([1,2,3],[4,5,6],[7,8,9])
mon_tableau3

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [43]:
# fonction d'agregations
import numpy as np
print("somme sur l'ensemble des elements:")
print(np.sum(iris))
#axis = 0 calcul par colonne
#axis = 1 calcul par ligne

print("somme par colonne :")
print(np.sum(iris, axis=0))
print('somme par ligne :')
print(np.sum(iris, axis=1))

somme sur l'ensemble des elements:
2378.7
somme par colonne :
[876.5 458.6 563.7 179.9 300. ]
somme par ligne :
[11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [44]:
import numpy as np
# mean moyenne std variance
print(np.mean(iris, axis=0))
print(np.std(iris, axis=0))



[5.84333333 3.05733333 3.758      1.19933333 2.        ]
[0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]


In [45]:
import numpy as np
print(np.max(iris, axis=0))
#max

[7.9 4.4 6.9 2.5 3. ]


In [55]:
iris3 = iris[iris[:,4]==3] # de type==
# calcul moyenne
print(np.mean(iris3, axis=0))

[6.588 2.974 5.552 2.026 3.   ]


In [56]:
# iris[iris[ les lignes, les colonnes]]
#recherche approfondi


In [57]:
# ajouter des elemnts 

np.append(notre_tableau,[21,22,23,24,25])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25])

In [58]:
np.append(iris,[[10,10,10,10,10]], axis=0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,  0.2,  1. ],
       [ 5. ,  3. ,  1.6,

In [59]:
import numpy
np.insert(notre_tableau, 1,42)
# l'element 42 a ete ajoute à lindex1
# donc a la place de la valeur 2 et la val 2 on tetrouve alors lindex 2

array([10, 42, 11, 12, 13, 14, 15, 16, 17, 18])

In [62]:
import numpy
np.insert(notre_tableau, 1,[42,43,44,45,46])

array([10, 42, 43, 44, 45, 46, 11, 12, 13, 14, 15, 16, 17, 18])

In [64]:
import numpy as np
np.insert(iris, 1,[10,10,10,10,10], axis =0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. , 10. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,

In [65]:
import numpy as np
np.insert(iris, 1,[10,10,10,10,10])

array([ 5.1, 10. , 10. , 10. , 10. , 10. ,  3.5,  1.4,  0.2,  1. ,  4.9,
        3. ,  1.4,  0.2,  1. ,  4.7,  3.2,  1.3,  0.2,  1. ,  4.6,  3.1,
        1.5,  0.2,  1. ,  5. ,  3.6,  1.4,  0.2,  1. ,  5.4,  3.9,  1.7,
        0.4,  1. ,  4.6,  3.4,  1.4,  0.3,  1. ,  5. ,  3.4,  1.5,  0.2,
        1. ,  4.4,  2.9,  1.4,  0.2,  1. ,  4.9,  3.1,  1.5,  0.1,  1. ,
        5.4,  3.7,  1.5,  0.2,  1. ,  4.8,  3.4,  1.6,  0.2,  1. ,  4.8,
        3. ,  1.4,  0.1,  1. ,  4.3,  3. ,  1.1,  0.1,  1. ,  5.8,  4. ,
        1.2,  0.2,  1. ,  5.7,  4.4,  1.5,  0.4,  1. ,  5.4,  3.9,  1.3,
        0.4,  1. ,  5.1,  3.5,  1.4,  0.3,  1. ,  5.7,  3.8,  1.7,  0.3,
        1. ,  5.1,  3.8,  1.5,  0.3,  1. ,  5.4,  3.4,  1.7,  0.2,  1. ,
        5.1,  3.7,  1.5,  0.4,  1. ,  4.6,  3.6,  1. ,  0.2,  1. ,  5.1,
        3.3,  1.7,  0.5,  1. ,  4.8,  3.4,  1.9,  0.2,  1. ,  5. ,  3. ,
        1.6,  0.2,  1. ,  5. ,  3.4,  1.6,  0.4,  1. ,  5.2,  3.5,  1.5,
        0.2,  1. ,  5.2,  3.4,  1.4,  0.2,  1. ,  4

In [66]:
np.delete(iris,1, axis=1)

array([[5.1, 1.4, 0.2, 1. ],
       [4.9, 1.4, 0.2, 1. ],
       [4.7, 1.3, 0.2, 1. ],
       [4.6, 1.5, 0.2, 1. ],
       [5. , 1.4, 0.2, 1. ],
       [5.4, 1.7, 0.4, 1. ],
       [4.6, 1.4, 0.3, 1. ],
       [5. , 1.5, 0.2, 1. ],
       [4.4, 1.4, 0.2, 1. ],
       [4.9, 1.5, 0.1, 1. ],
       [5.4, 1.5, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [4.8, 1.4, 0.1, 1. ],
       [4.3, 1.1, 0.1, 1. ],
       [5.8, 1.2, 0.2, 1. ],
       [5.7, 1.5, 0.4, 1. ],
       [5.4, 1.3, 0.4, 1. ],
       [5.1, 1.4, 0.3, 1. ],
       [5.7, 1.7, 0.3, 1. ],
       [5.1, 1.5, 0.3, 1. ],
       [5.4, 1.7, 0.2, 1. ],
       [5.1, 1.5, 0.4, 1. ],
       [4.6, 1. , 0.2, 1. ],
       [5.1, 1.7, 0.5, 1. ],
       [4.8, 1.9, 0.2, 1. ],
       [5. , 1.6, 0.2, 1. ],
       [5. , 1.6, 0.4, 1. ],
       [5.2, 1.5, 0.2, 1. ],
       [5.2, 1.4, 0.2, 1. ],
       [4.7, 1.6, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [5.4, 1.5, 0.4, 1. ],
       [5.2, 1.5, 0.1, 1. ],
       [5.5, 1.4, 0.2, 1. ],
       [4.9, 1

In [67]:
np.delete(iris,[1,2,3,4], axis=0) # sup index des ligne 1 2 3 4

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4

In [68]:
np.delete(notre_tableau,1)

array([10, 12, 13, 14, 15, 16, 17, 18])

In [69]:
#diviser un tab numpy

notre_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [70]:
import numpy as np
# sarrete a 2 et 6
notre_tableau1,notre_tableau2,notre_tableau3=np.split(notre_tableau, [2,6] )
print(notre_tableau1, notre_tableau2, notre_tableau3,  )

[[10 11 12]
 [13 14 15]] [[16 17 18]] []


In [71]:
# sur 1 tableau a 2 dimensions
# en sortie 2 tableau split
#vsplit ligne

array=np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("avant division")
print(array)
array1, array2 = np.vsplit(array, [2])
print('apres division')
print(array1)
print(array2)

avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
apres division
[[ 2.  5.  6.]
 [ 9. 10. 11.]]
[[5. 6. 9.]]


In [8]:
#hsplit pareil pour les colonnes

array=np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("avant division")
print(array)
array1, array2 = np.hsplit(array, [2])
print('apres division')
print(array1)
print(array2)

avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
apres division
[[ 2.  5.]
 [ 9. 10.]
 [ 5.  6.]]
[[ 6.]
 [11.]
 [ 9.]]


In [9]:
# concatener/combiner des tableaux

# () concatenate

array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9])
print(array1)
print(array2)
np.concatenate([array1,array2])

[1 2 3 4 5]
[6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float")
array2 = np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print(array1)
print(array2)
np.concatenate([array1,array2])

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.]])

In [11]:
array3= np.array([[4,10,13],[7,14,15]], dtype="float")
np.concatenate([array1, array2, array3])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.],
       [ 4., 10., 13.],
       [ 7., 14., 15.]])

In [4]:
# vstack() rajoute ou une ligne
# hstack()  ou colonne ( concatene)

# import numpy as np 

# array1 = np.array([15,16,47])
# array2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float")
# print(array1)
# print("___")
# print(array2)
# print("___")
# print(np.vstack([array1, array2]))
# array1 = np.array([[15,16,47]])
# print("___")
# print(array1)
# print("___")
# print(array2)
# print("___")
# print(np.hstack([array1, array2]))



In [12]:
moyenne = np.mean(iris, axis = 0)

print(np.insert(iris, 150, moyenne, axis = 0 ))


NameError: name 'iris' is not defined

In [4]:
import numpy as np
iris=np.genfromtxt("iris.csv", delimiter=";", skip_header=True, encoding="latin-1")
print('iris \n', iris)
iris2 = np.insert(iris, 1,[10,10,10,10,10])

print('iris+insert \n',iris2)

iris 
 [[4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1.6 0.6 1. ]
 [5.